services:
  bash_5_1_16:
    platform: ${DOCKER_PLATFORM}
    build:
      context: .
    volumes:
      - ${PWD}:/app
    working_dir: /app
    tty: true

    environment:
      - LANG=en_US.UTF-8
      - LANGUAGE=en_US:en
      - LC_ALL=en_US.UTF-8