services:
  42fractol:
    platform: ${DOCKER_PLATFORM}
    build:
      context: .
    volumes:
      - ${PWD}:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /app
    tty: true